### ISSUE TITLE
Old Sticker not downloaded because of a null id

### ISSUE THREAD

**Issue by reckter** [fabianonline/telegram_backup#113]
Hey,
When I try to download messages of a very old supergroup it fails with
```
java.lang.IllegalStateException: sticker["stickerset"].obj.get("id") must not be null
	at de.fabianonline.telegram_backup.mediafilemanager.StickerFileManager.getFilenameBase(StickerFileManager.kt:66)
	at de.fabianonline.telegram_backup.mediafilemanager.StickerFileManager.getTargetFilename(StickerFileManager.kt:72)
	at de.fabianonline.telegram_backup.Database.saveMessages(Database.kt:341)
	at de.fabianonline.telegram_backup.DownloadManager.downloadMessages(DownloadManager.kt:213)
	at de.fabianonline.telegram_backup.DownloadManager.downloadMessagesFromChannel(DownloadManager.kt:166)
	at de.fabianonline.telegram_backup.DownloadManager.downloadMessages(DownloadManager.kt:150)
	at de.fabianonline.telegram_backup.CommandLineController.<init>(CommandLineController.kt:173)
	at de.fabianonline.telegram_backup.CommandLineRunner.run(CommandLineRunner.kt:46)
	at de.fabianonline.telegram_backup.CommandLineRunnerKt.main(CommandLineRunner.kt:36)
```
I am currently using the master version of this tool:

Your version 1.1.3-71-g223a0fd seems to be a development version. Version check is disabled.
Telegram_Backup version 1.1.3-71-g223a0fd, Copyright (C) 2016, 2017 Fabian Schlenz

**Comment by reckter** [comment]
Fixed by #114
