### ISSUE TITLE
Error 500 of telegram api should not terminate the program

### ISSUE THREAD

**Issue by luckcolors** [fabianonline/telegram_backup#122]
Hello!
I've been using your tool and it seems it completely exits after the telegram apis returns an error 500, i think on this error it should just retry, (maybe implament some backaway logic). See the attached log.

```
500: RPC_MCGET_FAIL
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:209)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries$default(DefaultTelegramClient.kt:181)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:160)
        at com.github.badoualy.telegram.api.TelegramClient$DefaultImpls.executeRpcQuery(TelegramClient.kt:53)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQuery(DefaultTelegramClient.kt:157)
        at com.github.badoualy.telegram.tl.api.TelegramApiWrapper.messagesGetMessages(TelegramApiWrapper.java:673)
        at de.fabianonline.telegram_backup.DownloadManager.downloadMessages(DownloadManager.kt:274)
        at de.fabianonline.telegram_backup.DownloadManager.downloadMessages$default(DownloadManager.kt:241)
        at de.fabianonline.telegram_backup.DownloadManager._downloadMessages(DownloadManager.kt:150)
        at de.fabianonline.telegram_backup.DownloadManager.downloadMessages(DownloadManager.kt:82)
        at de.fabianonline.telegram_backup.CommandLineController.<init>(CommandLineController.kt:135)
        at de.fabianonline.telegram_backup.CommandLineRunnerKt.main(CommandLineRunner.kt:41)

----- EXIT -----
```

**Comment by luckcolors** [comment]
Let me know if you need any extra info.
