### ISSUE TITLE
ClosedChannelException

### ISSUE THREAD

**Issue by ffflorian** [fabianonline/telegram_backup#29]
While downloading media I got the following error (only once for now):
```java
Exception in thread "MTProtoWatchdog-exec-thread-1" java.lang.Error: java.nio.channels.ClosedChannelException
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
	at java.nio.channels.spi.AbstractSelectableChannel.configureBlocking(AbstractSelectableChannel.java:289)
	at com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection.unregister(MTProtoTcpConnection.kt:120)
	at com.github.badoualy.telegram.mtproto.MTProtoWatchdog.stop(MTProtoWatchdog.kt:132)
	at com.github.badoualy.telegram.mtproto.MTProtoWatchdog$run$2$1$1.run(MTProtoWatchdog.kt:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	... 2 more
```

**Comment by ffflorian** [comment]
Sorry for spamming. I saw the answer to that in the [FAQ](https://github.com/fabianonline/telegram_backup/blob/master/README.md#frequently-asked-questions) only now.
