### ISSUE TITLE
RpcErrorException while downloading

### ISSUE THREAD

**Issue by ItTakesTwo** [fabianonline/telegram_backup#41]
Because of a missing file the backup job crashes. Full stacktrace:
`RpcErrorException happened while downloading ./telegram_backup\+XXXXXXXXXX\files\101364.mp3
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:209)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries$default(DefaultTelegramClient.kt:181)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:171)
        at com.github.badoualy.telegram.api.TelegramClient$DefaultImpls.executeRpcQuery(TelegramClient.kt:56)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQuery(DefaultTelegramClient.kt:25)
        at de.fabianonline.telegram_backup.DownloadManager.downloadFileFromDc(DownloadManager.java:330)
        at de.fabianonline.telegram_backup.DownloadManager.downloadFile(DownloadManager.java:300)
        at de.fabianonline.telegram_backup.mediafilemanager.DocumentFileManager.download(DocumentFileManager.java:105)
        at de.fabianonline.telegram_backup.DownloadManager._downloadMedia(DownloadManager.java:276)
        at de.fabianonline.telegram_backup.DownloadManager.downloadMedia(DownloadManager.java:229)
        at de.fabianonline.telegram_backup.CommandLineController.<init>(CommandLineController.java:173)
        at de.fabianonline.telegram_backup.CommandLineRunner.main(CommandLineRunner.java:77)`

Maybe there should be an option to continue on errors or to at least skip missing files.

**Comment by frathe** [comment]
I checked out and compiles the .jar from the current master.
`RpcErrorException happened while downloading /Users/florianrathe/.telegram_backup/+491702417877/files/376507.mp4
420: FLOOD_WAIT_588
	at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:209)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries$default(DefaultTelegramClient.kt:181)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:171)
	at com.github.badoualy.telegram.api.TelegramClient$DefaultImpls.executeRpcQuery(TelegramClient.kt:56)
	at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQuery(DefaultTelegramClient.kt:25)
	at de.fabianonline.telegram_backup.DownloadManager.downloadFileFromDc(DownloadManager.java:333)
	at de.fabianonline.telegram_backup.DownloadManager.downloadFile(DownloadManager.java:300)
	at de.fabianonline.telegram_backup.mediafilemanager.DocumentFileManager.download(DocumentFileManager.java:105)
	at de.fabianonline.telegram_backup.DownloadManager._downloadMedia(DownloadManager.java:276)
	at de.fabianonline.telegram_backup.DownloadManager.downloadMedia(DownloadManager.java:229)
	at de.fabianonline.telegram_backup.CommandLineController.<init>(CommandLineController.java:173)
	at de.fabianonline.telegram_backup.CommandLineRunner.main(CommandLineRunner.java:77)

----- EXIT -----`
