### ISSUE TITLE
New issue? Or repeat?

### ISSUE THREAD

**Issue by SnowMink** [fabianonline/telegram_backup#52]
I looked around an seen the MTProtowatchdog error pop up previously, but I am more curious about this. I am thinking I'm seeing it list chat messages numerically like this?

.31800...32000...32200...32400...32600...32800...33000...33200...33400...33600.
..33800...34000...34200...34400...34600...34800...35000...35200Exception in thre
ad "RxComputationThreadPool-3" java.lang.IllegalStateException: Exception thrown
 on Scheduler.Worker thread. Add `onError` handling.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: rx.exceptions.OnErrorNotImplementedException: Reached end-of-stream
        at rx.Observable$26.onError(Observable.java:7881)
        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
        at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.jav
a:71)
        at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.jav
a:71)
        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue
(OperatorObserveOn.java:191)
        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(Op
eratorObserveOn.java:162)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        ... 7 more
Caused by: java.io.IOException: Reached end-of-stream
        at com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection.r
eadBytes(MTProtoTcpConnection.kt:143)
        at com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection.r
eadBytes$default(MTProtoTcpConnection.kt:134)
        at com.github.badoualy.telegram.mtproto.transport.MTProtoTcpConnection.r
eadMessage(MTProtoTcpConnection.kt:65)
        at com.github.badoualy.telegram.mtproto.MTProtoWatchdog.readMessage(MTPr
otoWatchdog.kt:94)
        at com.github.badoualy.telegram.mtproto.MTProtoWatchdog.access$readMessa
ge(MTProtoWatchdog.kt:18)
        at com.github.badoualy.telegram.mtproto.MTProtoWatchdog$run$2$1$1.run(MT
ProtoWatchdog.kt:56)
        ... 3 more
...35400...35600...35800...36000...36200...36400...36600...36800...37000...37200
...37400...37600...37800...38000...38200...38400

That number sequence? As it is downloading chat text atm, nothing else I assume those download first.

**Comment by fabianonline** [comment]
Yes, the numbers are indeed the downloaded message IDs.

The error messages from the watchdog can be ignored; they doesn't pose a problem, but I can't disable them. :-/
