### ISSUE TITLE
Error LOCATION_INVALID while downloading media

### ISSUE THREAD

**Issue by viaggio32** [fabianonline/telegram_backup#54]
`.RpcErrorException happened while downloading C:\Users\viagg\.telegram_backup\+39XXXXXXXXXX\files\246206.ogg
400: LOCATION_INVALID
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:209)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries$default(DefaultTelegramClient.kt:181)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:160)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:166)
        at com.github.badoualy.telegram.api.TelegramClient$DefaultImpls.executeRpcQuery(TelegramClient.kt:56)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQuery(DefaultTelegramClient.kt:25)
        at de.fabianonline.telegram_backup.DownloadManager.downloadFileFromDc(DownloadManager.java:330)
        at de.fabianonline.telegram_backup.DownloadManager.downloadFile(DownloadManager.java:300)
        at de.fabianonline.telegram_backup.mediafilemanager.DocumentFileManager.download(DocumentFileManager.java:105)
        at de.fabianonline.telegram_backup.DownloadManager._downloadMedia(DownloadManager.java:276)
        at de.fabianonline.telegram_backup.DownloadManager.downloadMedia(DownloadManager.java:229)
        at de.fabianonline.telegram_backup.CommandLineController.<init>(CommandLineController.java:173)
        at de.fabianonline.telegram_backup.CommandLineRunner.main(CommandLineRunner.java:77)

----- EXIT -----`

**Comment by ximocoder** [comment]
the same problem as me... do you get it after downloading some files?

**Comment by viaggio32** [comment]
yes, after 31600 files

**Comment by morgenst3rn** [comment]
Same error here, i have a lot less files than viaggio32, i'm trying to locate the audio file that is causing this error, but to no avail, telegram won't search into the filenames of the media....

C:\Users\***\Desktop>java -jar telegram_backup.jar --account +39***
Telegram_Backup version 1.0.6, Copyright (C) 2016 Fabian Schlenz

Telegram_Backup comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
welcome to redistribute it under certain conditions; run it with '--license' for details.

Base directory for files: C:\Users\***\.telegram_backup
You are logged in as *** (@***)
Opening database...
Database version: 7
Database is ready.
Downloading most recent dialogs...
Top message ID is 66802
Top message ID in database is 66611
Downloading 191 messages.
...191 done.
Checking message database for completeness...
Checking and downloading media.
Legend:
'V' - Video         'P' - Photo         'D' - Document
'S' - Sticker       'A' - Audio         'G' - Geolocation
'.' - Previously downloaded file        'e' - Empty file
' ' - Ignored media type (weblinks or contacts, for example)
'x' - File skipped because of timeout errors
5463 Files to check / download
................... ...................................   ..............    ........................ - 100/5463
................................RpcErrorException happened while downloading C:\Users\***\.telegram_backup\+39***\files\2253.ogg
400: LOCATION_INVALID
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:209)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries$default(DefaultTelegramClient.kt:181)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:160)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:166)
        at com.github.badoualy.telegram.api.TelegramClient$DefaultImpls.executeRpcQuery(TelegramClient.kt:56)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQuery(DefaultTelegramClient.kt:25)
        at de.fabianonline.telegram_backup.DownloadManager.downloadFileFromDc(DownloadManager.java:330)
        at de.fabianonline.telegram_backup.DownloadManager.downloadFile(DownloadManager.java:300)
        at de.fabianonline.telegram_backup.mediafilemanager.DocumentFileManager.download(DocumentFileManager.java:105)
        at de.fabianonline.telegram_backup.DownloadManager._downloadMedia(DownloadManager.java:276)
        at de.fabianonline.telegram_backup.DownloadManager.downloadMedia(DownloadManager.java:229)
        at de.fabianonline.telegram_backup.CommandLineController.<init>(CommandLineController.java:173)
        at de.fabianonline.telegram_backup.CommandLineRunner.main(CommandLineRunner.java:77)

----- EXIT -----

**Comment by aliakbarRashidi** [comment]
this was fixed.( problem was in the kotlogram lib)

**Comment by ximocoder** [comment]
Some way of getting the latest version with the kotlogram lib for windows?

**Comment by fabianonline** [comment]
No, you can't just update the library (otherwise I'd be happy to just do it myself...).

Did this bug occur in the last time? Or was it maybe a bug on Telegram's side?
